// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  console.log("Running");

  d3.csv("datamanip/ontime_geohashes.csv", function(csv) {
    var all, cf, dimensions, groups;
    console.log("Loaded csv, number of rows: " + csv.length);
    cf = crossfilter(csv);
    all = cf.groupAll();
    console.log("Creating dimensions ...");
    dimensions = {
      Origin: cf.dimension(function(d) {
        return d.Origin;
      }),
      GeoHashPair: cf.dimension(function(d) {
        return "" + d.Origin_Hash + "," + d.Dest_Hash;
      }),
      GeoHashLevel2Pair: cf.dimension(function(d) {
        return "" + d.Origin_Hash.slice(0, 2) + "->" + d.Dest_Hash.slice(0, 2);
      })
    };
    console.log("Created dimensions");
    console.log("Creating groups ...");
    groups = {
      GeoHashLevel2Pair: dimensions.GeoHashLevel2Pair.group()
    };
    console.log("Created groups");
    dc.pieChart("#geohash-level2-chart").dimension(dimensions.GeoHashLevel2Pair).group(groups.GeoHashLevel2Pair).renderLabel(true);
    dc.dataTable(".dc-data-table").dimension(dimensions.Origin).group(function(d) {
      return d;
    }).columns([
      function(d) {
        return d.Origin;
      }, function(d) {
        return d.Origin_Hash;
      }, function(d) {
        return d.Dest;
      }, function(d) {
        return d.Dest_Hash;
      }
    ]).sortBy(function(d) {
      return "" + d.Origin + "-" + d.Dest;
    }).order(d3.ascending);
    return dc.renderAll();
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
