// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  console.log("Running");

  d3.csv("datamanip/ontime_geohashes.csv", function(csv) {
    var all, cf, dimensions;
    console.log("Loaded csv, number of rows: " + csv.length);
    cf = crossfilter(csv);
    all = cf.groupAll();
    console.log("Creating dimensions ...");
    dimensions = {
      Origin: cf.dimension(function(d) {
        return d.Origin;
      })
    };
    console.log("Created dimensions");
    dc.dataTable(".dc-data-table").dimension(dimensions.Origin).group(function(d) {
      return d;
    }).columns([
      function(d) {
        return d.Origin;
      }, function(d) {
        return d.Dest;
      }
    ]).sortBy(function(d) {
      return "" + d.Origin + "-" + d.Dest;
    }).order(d3.ascending);
    return dc.renderAll();
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
