// Generated by CoffeeScript 1.6.3
(function() {
  var argv, csv, fs,
    _this = this;

  fs = require('fs');

  csv = require('csv');

  argv = require('optimist').argv;

  if (!(argv.airports && argv.geohashes)) {
    console.error("Usage: " + argv.$0 + " --airports <input csv file> --geohashes <output csv file>");
    process.exit(1);
  }

  csv().from.path("" + __dirname + "/" + argv.airports, {
    delimiter: ',',
    escape: '"',
    columns: true
  }).to.stream(fs.createWriteStream("" + __dirname + "/" + argv.geohashes)).on('record', function(row, index) {
    return console.log('#' + index + ' ' + JSON.stringify(row));
  }).on('close', function(count) {
    return console.log("Number of lines: " + count);
  }).on('error', function(error) {
    return console.error(error.message);
  });

}).call(this);

/*
//@ sourceMappingURL=createGeoHashesForAirports.map
*/
