// Generated by CoffeeScript 1.6.3
(function() {
  var argv, csv, fs, geohash,
    _this = this;

  fs = require('fs');

  csv = require('csv');

  geohash = require('ngeohash');

  argv = require('optimist').argv;

  if (!(argv.airports && argv.geohashes)) {
    console.error("Usage: " + argv.$0 + " --airports <input csv file> --geohashes <output csv file>");
    process.exit(1);
  }

  csv().from.path("" + __dirname + "/" + argv.airports, {
    delimiter: ',',
    escape: '"',
    columns: true
  }).to.stream(fs.createWriteStream("" + __dirname + "/" + argv.geohashes), {
    columns: ['iata', 'hash']
  }).transform(function(row) {
    var hash, lat, lon;
    lat = parseFloat(row.lat);
    lon = parseFloat(row.long);
    hash = geohash.encode(lat, lon);
    return {
      iata: row.iata,
      hash: hash
    };
  }).on('record', function(row, index) {
    return console.log('#' + index + ' ' + JSON.stringify(row));
  }).on('close', function(count) {
    return console.log("Number of lines: " + count);
  }).on('error', function(error) {
    return console.error(error.message);
  });

}).call(this);

/*
//@ sourceMappingURL=createGeoHashesForAirports.map
*/
